const images = {
    airbnb: '/assets/airbnb.png',
    apple: '/assets/apple.svg',
    arrow_up: '/assets/arrow-up.svg',
    bill: '/assets/bill.png',
    binance: '/assets/binance.png',
    card: '/assets/card.png',
    close: '/assets/close.svg',
    coinbase: '/assets/coinbase.png',
    Discount: '/assets/Discount.svg',
    dropbox: '/assets/dropbox.png',
    facebook: '/assets/facebook.svg',
    google: '/assets/google.svg',
    instagram: '/assets/instagram.svg',
    linkedin: '/assets/linkedin.svg',
    logo: '/assets/logo.svg',
    menu: '/assets/menu.svg',
    people01: '/assets/people01.png',
    people02: '/assets/people02.png',
    people03: '/assets/people03.png',
    quotes: '/assets/quotes.svg',
    robot: '/assets/robot.png',
    Send: '/assets/Send.svg',
    Shield: '/assets/Shield.svg',
    Star: '/assets/Star.svg',
    twitter: '/assets/twitter.svg',
}

export default images